// Ordered hymn data provided by the user. Titles are preserved exactly once.
const hymns = [
  "Abide With Me",
  "Alas And Did My Saviour Bleed",
  "All Creatures Of Our God And King",
  "All Glory Laud And Honour",
  "All Hail The Power Of Jesus Name",
  "All My Hope On God Is Founded",
  "All People That On Earth Do Dwell",
  "All The Way My Saviour Leads Me",
  "All Things Bright And Beautiful",
  "Amazing Grace",
  "And Can It Be",
  "Are You Washed In The Blood",
  "Be Still And Know That I Am God",
  "Blessed Assurance",
  "Breathe On Me Breath Of God",
  "Christ The Lord Is Risen Today",
  "Come Let Us Sing Of A Wonderful Love",
  "Come Thou Fount Of Every Blessing",
  "Come Ye Thankful People Come",
  "Count Your Blessings",
  "Crown Him With Many Crowns",
  "Dear Lord And Father Of Mankind",
  "Eternal Father Strong To Save",
  "Father Hear The Prayer We Offer",
  "For All The Saints",
  "Give Me Oil In My Lamp",
  "Glorious Things Of Thee Are Spoken",
  "Grace Greater Than Our Sin",
  "Great Is Thy Faithfulness",
  "Guide Me O Thou Great Jehovah",
  "Hallelujah What A Saviour",
  "He Leadeth Me",
  "Here Is Love",
  "Holy Holy Holy",
  "How Firm A Foundation",
  "How Sweet The Name Of Jesus Sounds",
  "I Know Whom I Have Believed",
  "Immortal Invisible",
  "I Need Thee Every Hour",
  "In The Garden",
  "I Stand Amazed",
  "I Surrender All",
  "It Is Well With My Soul",
  "I Will Sing The Wondrous Story",
  "Jerusalem (Forevermore)",
  "Jesus Keep Me Near The Cross",
  "Jesus Loves Me (This I Know)",
  "Jesus Paid It All",
  "Jesus The Name High Over All",
  "Just As I Am",
  "King Of My Life I Crown Thee Now",
  "Leaning On The Everlasting Arms",
  "Lord For The Years",
  "Love Divine",
  "Love Lifted Me",
  "Low In The Grave He Lay",
  "My Jesus I Love Thee",
  "My Song Is Love Unknown",
  "Nothing But The Blood",
  "Now Thank We All Our God",
  "O Breath Of Life",
  "O For A Thousand Tongues To Sing",
  "O God Our Help In Ages Past",
  "O Jesus I Have Promised",
  "O Love That Will Not Let Me Go",
  "O Praise Ye The Lord",
  "O The Deep Deep Love Of Jesus",
  "O Thou Who Camest From Above",
  "O Worship The King",
  "O Worship The Lord In The Beauty Of Holiness",
  "Power In The Blood",
  "Praise God From Whom All Blessings Flow",
  "Praise My Soul The King Of Heaven",
  "Praise To The Lord The Almighty",
  "Rock Of Ages",
  "Softly And Tenderly",
  "Standing On The Promises",
  "Take My Life And Let It Be",
  "Tell Out My Soul",
  "The Church’s One Foundation",
  "The King Of Love",
  "The Lord’s My Shepherd",
  "The Old Rugged Cross",
  "There Is A Fountain",
  "There Is A Green Hill Far Away",
  "The Solid Rock",
  "Thine Be The Glory",
  "Thou Whose Almighty Word",
  "Thy Hand O God Has Guided",
  "’Tis So Sweet To Trust In Jesus",
  "To God Be The Glory",
  "Turn Your Eyes Upon Jesus",
  "We Plough The Fields And Scatter",
  "We Rest On Thee",
  "Were You There",
  "What A Friend We Have In Jesus",
  "When I Survey The Wondrous Cross (Rockingham)",
  "When The Roll Is Called Up Yonder",
  "When We Walk With The Lord (Trust And Obey)",
  "Will Your Anchor Hold"
];
